spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

    datasource:
      url: jdbc:mysql://localhost:3306/personal_finance
      username: root
      password:
      driverClassName: com.mysql.cj.jdbc.Driver